#ifndef IMAGEANALYZER_GLOBAL_H
#define IMAGEANALYZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEANALYZER_LIBRARY)
#  define IMAGEANALYZER_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEANALYZER_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEANALYZER_GLOBAL_H
